apiVersion: v1
kind: Service
metadata:
  name: webapp-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - name: webapp
      protocol: TCP
      port: 80
      targetPort: 8080
