apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
    # matchExpressions:
    #   - { key:app, operator: In, values: [webapp, webserver] }
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: kodega2016/kube_action
          ports:
            - containerPort: 8080
