apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: kodega2016/kube_action
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - name: webapp
      protocol: TCP
      port: 80
      targetPort: 8080
